# fly.toml app configuration file generated for delegationz on 2023-06-30T10:52:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delegationz"
primary_region = "cdg"

[build]
  dockerfile = "utils/dockerfiles/delegationz.dockerfile"
  ignorefile = ".dockerignore"
  [build.args]
    cmd = "delegationz"
    version = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
