output   = "pkg/repository"
pkgname = "repository"
wipe     = true
no-tests = false
add-enum-types = true

[psql]
  dbname = "dev"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "supersecret"
  schema = "public"
  sslmode = "disable"
  blacklist = ["_prisma_migrations", "information_schema"]