// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

var TableNames = struct {
	Delegations      string
	DelegationsStats string
	Delegators       string
}{
	Delegations:      "delegations",
	DelegationsStats: "delegations_stats",
	Delegators:       "delegators",
}
