name: Continuous Integration

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Run unit tests
        run: |
          make test | tee -a out.txt
          cat out.txt >> $GITHUB_STEP_SUMMARY
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov

  build_containers:
    # environment:
    #   name: ${{ github.ref_name }}
    #   url: "${{ vars.DEPLOY_URL }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        cmds: ["api", "delegationz", "importer"]
    steps:
      - uses: actions/checkout@v3
      - name: Login to  Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # ## Build and push to container registry
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            cmd=${{ matrix.project }}
            version=${{ env.VERSION_ARG }}
          file: golang.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
